    - name: Windows_x64
      os: windows
      language: cpp

      env:
        - PATH=/c/Python39:/c/Python39/Scripts:$PATH
        - QT_VERSION=5.15.2
        - QIF_VERSION=4.4
        - QT_BIN_DIR="c:\\Qt\\$QT_VERSION\\msvc2019_64\\bin"
        - QIF_BIN_DIR="c:\\Qt\\Tools\\QtInstallerFramework\\${QIF_VERSION}\\bin"
        - BUILD_ARCH=64
        - MSVC_PATH_WIN="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community"
        - MSVC_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2019/Community"

      install:
        - if [ ! -f "$MSVC_PATH/VC/Auxiliary/Build/vcvars64.bat" ]; then choco install --ignorepackagecodes --no-progress -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended --nocache --installPath $MSVC_PATH_WIN"; fi
        - if [ ! -f /C/Qt/$QT_VERSION/msvc2019_64/bin/qmake ]; then choco install python --version 3.9.1; fi
        - |
          if [ ! -f /C/Qt/$QT_VERSION/msvc2019_64/bin/qmake ]; then \
          python -m pip install --upgrade pip && \
          pip3 install -U aqtinstall requests py7zr && \
          pip3 show aqtinstall && \
          aqt install-qt windows desktop $QT_VERSION win64_msvc2019_64 -m all -O /C/Qt && \
          aqt install-tool windows desktop tools_ifw  -O /C/Qt ; \
          fi

      script:
        - echo set BUILD_ARCH=$BUILD_ARCH > winbuild.bat
        - echo set QT_BIN_DIR="$QT_BIN_DIR" >> winbuild.bat
        - echo set QIF_BIN_DIR="$QIF_BIN_DIR" >> winbuild.bat
        - echo call \""%MSVC_PATH_WIN%\\VC\\Auxiliary\\Build\\vcvars${BUILD_ARCH}.bat\"" >> winbuild.bat
        - echo call \""%MSVC_PATH_WIN%\\Common7\\Tools\\VsDevCmd.bat\" -arch=amd64" >> winbuild.bat
        - echo call deploy\\build_windows.bat >> winbuild.bat
        - cmd //c winbuild.bat
        
      deploy:
        provider: releases
        token: $GH_TOKEN
        cleanup: false
        file:
        - "AmneziaVPN_x64.exe"
        on:
          tags: true
          branch: master

      cache:
        directories:
          - /C/Qt
          - $MSVC_PATH
